require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.6.3
  Severity: warning
  Exclude:
   - "db/migrate/*"
   - "db/*/"
   - "tmp/*/"
   - "vendor/*/"
   - "bin/*/"
   - "log/*/"
   - "node_modules/**/*"

# Guiding principle of classes is Single Responsibility Principle (SRP), SRP can't be accurately measured by Lines of Code
Metrics/ClassLength:
  Enabled: false

# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength:
  Max: 15

#Checks the block length, which is large sometimes in general
Metrics/BlockLength:
  Enabled: false

# Commonly used screens these days easily fit more than 80 characters.
Metrics/LineLength:
  Max: 120

# Single quotes being faster is hardly measurable and only affects parse time.
# Enforcing double quotes reduces the times where you need to change them
# when introducing an interpolation. Use single quotes only if their semantics
# are needed.
Style/StringLiterals:
  EnforcedStyle: double_quotes

# This cop makes sure that certain binary operator methods have their sole parameter named other.
# I think it will be confusing calling the argument 'other' in all such cases
Naming/BinaryOperatorParameterName:
  Enabled: false

# We are not writing any comments during coding
Documentation:
  Enabled: false

#Frozen string literal is default in Ruby3.0, also
#The frozen string literal comment is only valid in Ruby 2.3+.
#causes issues in spec files , CHECK IF OKAY
Style/FrozenStringLiteralComment:
  Enabled: false

#This cop tries to produce a complexity score that's a measure of the complexity the reader experiences when looking at a method.
#CHECK THIS, I couldn't figure out much importance
Metrics/PerceivedComplexity:
  Enabled: false

# The cyclomatic complexity is the number of linearly independent paths through a method.
# The algorithm counts decision points and adds one
#CHECK FOR MAX VALUE default is 6

Metrics/CyclomaticComplexity:
  Max: 8
# Enabled: false

# its the [A]ssignemnts, [B]ranches, and [C]onditions size,
#CHECK MAX VALUE REQUIREMENT, default is 15
Metrics/AbcSize:
  Max: 18
# Enabled: false

#Enforces use of %i or %I for an array of symbols, which is not required
Style/SymbolArray:
  Enabled: false

#method naming convention
Naming/AccessorMethodName:
  Enabled: true

# The space here provides no real gain in readability while consuming
Layout/SpaceInsideBlockBraces:
 SpaceBeforeBlockParameters: true

Layout/SpaceInsideHashLiteralBraces:
 EnforcedStyle: space

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

 # Rubocop is marking variables used as useless in specs.
Lint/UselessAssignment:
  Exclude:
    - "spec/*/"
  Enabled: false
