version: '3.4'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root

  app:
    build: .
    volumes:
      - .:/app
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
